export type Solution = {
  slug: string;
  number: string;
  title: string;
  shortTitle: string;
  description: string;
  image: string;
  intro: string;
  benefits: string[];
  applications: string[];
};

export const solutions: Solution[] = [
  {
    slug: "operation-theater-manufacturer",
    number: "OT",
    title: "Operation Theater Manufacturer in Maharashtra",
    shortTitle: "Operation Theater Manufacturer in Maharashtra",
    description: "Operation theater manufacturer in Maharashtra providing modular operation theater and OT solutions for hospitals, with engineered airflow, hygiene, safety and installation support.",
    image: "/solutions/1 (6).png",
    intro: "Airtec Solutions specializes in comprehensive operation theater solutions for hospitals in Pune, Maharashtra and across India. We understand the critical importance of a well-designed and equipped operation theater in delivering safe and efficient healthcare services.",
    benefits: ["Sterilized and modular operation theater systems", "Planning, design, manufacturing and installation support", "HVAC, HEPA filtration and controlled-environment expertise", "Solutions coordinated around clinical workflow and equipment"],
    applications: ["Hospitals", "Research institutes", "Medical colleges", "Advanced surgical facilities"],
  },
  {
    slug: "modular-operation-theater-manufacturer",
    number: "01",
    title: "Modular Operation Theatre",
    shortTitle: "Modular OT",
    description: "Turnkey modular operation theatre solutions for hygienic, controlled and efficient surgical environments.",
    image: "/solutions/1 (6).png",
    intro: "Airtec Solutions designs and installs modular operation theatres around the clinical workflow, room classification and infection-control requirements of each healthcare facility. From room planning and hygienic finishes to airflow coordination and commissioning support, our team helps create a dependable surgical environment.",
    benefits: ["Hygienic, easy-to-maintain wall and ceiling finishes", "Layout planning around surgical workflow and equipment", "Coordinated HVAC, HEPA filtration and pressure control", "Installation, testing and commissioning support"],
    applications: ["Major operation theatres", "Minor operation theatres", "Specialised surgical rooms", "Hospital renovation and expansion projects"],
  },
  {
    slug: "modular-clean-room-system-manufacturer",
    number: "02",
    title: "Modular Clean Room System manufacturer",
    shortTitle: "Modular Clean Room System manufacturer",
    description: "Airtec Solutions creates controlled environments that prevent contamination for pharmaceutical companies, healthcare centres, biotechnology firms, electronics companies, and research facilities throughout India.",
    image: "/solutions/1 (5).png",
    intro: "Our modular cleanroom systems combine engineered panels, sealed interfaces, controlled airflow and practical access planning. Each cleanroom is developed around the required cleanliness classification, temperature, humidity, pressure differential and process needs.",
    benefits: ["Flexible modular construction for future changes", "Smooth, sealed and cleanable internal surfaces", "Airflow and pressure strategy aligned to the process", "Single-point coordination from design through handover"],
    applications: ["Pharmaceutical production", "Medical device manufacturing", "Biotechnology and research", "Healthcare and laboratory environments"],
  },
  {
    slug: "hvac-hepa-filtration",
    number: "03",
    title: "HVAC & HEPA Filtration",
    shortTitle: "HVAC & HEPA",
    description: "Air handling, HVAC and HEPA filtration systems designed to maintain the environmental conditions critical processes require.",
    image: "/solutions/1 (4).png",
    intro: "Airtec integrates HVAC and HEPA filtration into the wider clean-environment design. We consider air changes, filtration, temperature, humidity, pressure relationships and maintainability so the installed system supports both people and process.",
    benefits: ["Application-led air handling and filtration design", "HEPA filtration for high-control areas", "Balanced airflow and pressure-differential planning", "Accessible maintenance and service considerations"],
    applications: ["Cleanrooms and controlled production areas", "Operation theatres and critical care spaces", "Laboratories and research facilities", "Medical and pharmaceutical applications"],
  },
  {
    slug: "laminar-airflow-systems",
    number: "04",
    title: "Laminar Airflow Systems",
    shortTitle: "Laminar Airflow",
    description: "Unidirectional airflow systems that provide a controlled clean-air zone for sensitive operations and processes.",
    image: "/solutions/1 (3).png",
    intro: "Laminar airflow systems create a focused zone of unidirectional, filtered air for work that needs protection from airborne contamination. Airtec helps select and configure the right system around the working area, product, operator and cleaning routine.",
    benefits: ["Focused unidirectional airflow at the work zone", "HEPA-filtered air for contamination-sensitive tasks", "Configurations suited to process and available space", "Practical construction for routine cleaning and upkeep"],
    applications: ["Aseptic and sterile preparation", "Laboratory workstations", "Medical device assembly", "Sampling and inspection activities"],
  },
  {
    slug: "cleanroom-equipment",
    number: "05",
    title: "Cleanroom Equipment",
    shortTitle: "Cleanroom Equipment",
    description: "Clean-air and material-transfer equipment including pass boxes, air showers, sampling booths and dispensing booths.",
    image: "/solutions/1 (2).png",
    intro: "The right equipment helps protect cleanroom zoning and makes material and personnel movement more controlled. Airtec supplies specialist cleanroom equipment selected for the layout, transfer path and operating procedure of the facility.",
    benefits: ["Pass boxes for controlled material transfer", "Air showers and air curtains for contamination control", "Sampling and dispensing booths for process protection", "Equipment coordinated with panels, doors and HVAC"],
    applications: ["Pharmaceutical material handling", "Dispensing and sampling areas", "Medical device production", "Laboratories and controlled stores"],
  },
  {
    slug: "cleanroom-panels-doors",
    number: "06",
    title: "Cleanroom Panels & Doors",
    shortTitle: "Panels & Doors",
    description: "Engineered cleanroom wall, ceiling, door and window systems for sealed, hygienic modular environments.",
    image: "/solutions/1 (1).png",
    intro: "Cleanroom envelopes must support hygiene, airflow performance and long-term maintenance. Airtec provides coordinated panels, doors, windows and ceiling systems with details developed for cleanability, durability and a consistent finished environment.",
    benefits: ["Smooth, hygienic surfaces with sealed junctions", "Panel and ceiling layouts coordinated to services", "Cleanroom doors and windows for controlled access and visibility", "Material selection matched to use and maintenance needs"],
    applications: ["Modular cleanroom construction", "Hospital and OT interiors", "Pharma and medical device facilities", "Laboratory and controlled support spaces"],
  },
  {
    slug: "laminar-workstation-manufacturer",
    number: "07",
    title: "Laminar Flow Workstation",
    shortTitle: "Laminar Workstation",
    description: "Vertical laminar flow workstations engineered for cleanroom processes that demand controlled, filtered air.",
    image: "/solutions/1 (3).png",
    intro: "Airtec Solutions supplies laminar flow workstations for cleanroom processes where a focused zone of filtered, unidirectional air helps protect the work, operator and product from airborne contamination.",
    benefits: ["Vertical laminar airflow for critical work zones", "Filtered clean air to support contamination control", "Stainless steel or mild-steel construction options", "Custom sizing and configuration for the application"],
    applications: ["Cleanroom workstations", "Aseptic preparation", "Laboratory processes", "Precision assembly and inspection"],
  },
  {
    slug: "pressure-module-in-pune",
    number: "08",
    title: "Positive Pressure Module in Pune",
    shortTitle: "Pressure Module",
    description: "Automatic positive and negative pressure modules designed to support clean, controlled environments in compact spaces and work zones.",
    image: "/solutions/1 (4).png",
    intro: "Airtec Solutions supplies pressure modules for cleanrooms and controlled work areas where positive pressure, filtered air and practical contamination control are essential to the process.",
    benefits: ["Positive-pressure support to help limit contaminated air ingress", "HEPA-filtered supply air for controlled spaces", "Automatic operation with coordinated cooling and airflow", "Durable GI powder-coated construction"],
    applications: ["Cleanrooms", "Controlled production areas", "Laboratories", "Compact process enclosures"],
  },
  {
    slug: "aluminium-coving",
    number: "09",
    title: "Aluminium Covings",
    shortTitle: "Aluminium Covings",
    description: "Anodized and powder-coated aluminium coving accessories for hygienic cleanroom and modular operation theatre junctions.",
    image: "/solutions/1 (1).png",
    intro: "Airtec Solutions supplies aluminium covings and coordinated room-corner accessories that help complete smooth, cleanable transitions within modular cleanrooms and operation theatres.",
    benefits: ["Smooth wall-to-wall and wall-to-ceiling transitions", "Anodized or powder-coated aluminium finish options", "Designed for modular cleanroom and OT integration", "Supports cleanable, hygienic internal detailing"],
    applications: ["Modular cleanrooms", "Modular operation theatres", "Controlled production areas", "Hygienic room-corner detailing"],
  },
  {
    slug: "clean-air-system-manufacturer",
    number: "10",
    title: "Clean Air System Manufacturer",
    shortTitle: "Clean Air System",
    description: "Fully automatic air shower and clean-air systems that give personnel a high-velocity clean-air wash before controlled-area entry.",
    image: "/solutions/1 (2).png",
    intro: "Airtec Solutions makes air showers, clean-air systems and clean-air pressure modules for controlled environments where a disciplined personnel entry sequence helps protect the room from contaminants.",
    benefits: ["High-velocity clean-air wash before entry", "Interlocked access to help contain contaminants", "Modular single or tunnel configurations", "Factory-tested construction with durable finish options"],
    applications: ["Hospitals", "Pharmaceutical and drug manufacturing", "Life science and biomedical research", "Microelectronics, aerospace and precision manufacturing"],
  },
  {
    slug: "softwall-operation-theater",
    number: "11",
    title: "Softwall Operation Theater",
    shortTitle: "Softwall OT",
    description: "Modular, portable softwall operation theater solutions with galvanized stainless-steel construction for hospitals across India.",
    image: "/solutions/1 (6).png",
    intro: "Airtec Solutions manufactures and supplies Softwall Operation Theater systems for hospitals across India. Built with stainless steel and a galvanized surface treatment, each modular system is designed for straightforward installation, portability and dependable use in healthcare environments.",
    benefits: ["Stainless-steel construction for hygienic healthcare environments", "Modular build for flexible configuration and installation", "Galvanized surface treatment for a durable finish", "Easy-installable, portable system made in India by Airtec Solutions"],
    applications: ["Hospitals", "Temporary surgical facilities", "Healthcare expansion projects", "Hospital projects across India"],
  },
  {
    slug: "semi-modular-operation-theater-manufacturer",
    number: "12",
    title: "Semi Modular Operation Theater",
    shortTitle: "Semi Modular OT",
    description: "GI-painted semi modular operation theater systems with a durable, high-quality finish for hospitals across India.",
    image: "/solutions/1 (6).png",
    intro: "Airtec Solutions manufactures Semi Modular Operation Theater systems for hospitals, research institutes and medical colleges. Each pre-fabricated system brings together a fine-finished GI steel structure and sterile coating details to create a robust, durable healthcare interior.",
    benefits: ["GI-painted construction with a high-quality finish", "Durable, robust surfaces for healthcare use", "Semi-modular approach that works with the existing civil structure", "Manufactured in India and supplied across India"],
    applications: ["Hospitals", "Operation theaters", "Research institutes", "Medical colleges"],
  },
  {
    slug: "sterilized-operation-theater-manufacturer",
    number: "13",
    title: "Sterilized Operation Theater Manufacturer",
    shortTitle: "Sterilized OT",
    description: "PPGI modular sterilized operation theaters with a high-quality finish, long durability and robust construction for hospitals across India.",
    image: "/solutions/1 (6).png",
    intro: "Airtec Solutions manufactures Sterilized Operation Theater systems for hospitals, research institutes and medical colleges. These pre-fabricated modular systems use quality-compliant raw materials and a fine-finished steel structure with sterile coating details.",
    benefits: ["PPGI modular construction for a finished clinical interior", "Sterile coating with high-quality finish and robustness", "Long-lasting surfaces designed for hospital use", "Manufactured in India and supplied across India"],
    applications: ["Hospitals", "Operation theaters", "Research institutes", "Medical colleges"],
  },
  {
    slug: "prefabricated-operation-theater",
    number: "14",
    title: "Prefabricated Operation Theater",
    shortTitle: "Prefabricated OT",
    description: "Easy-install, portable prefabricated modular operation theaters with complete HVAC support for hospitals.",
    image: "/solutions/1 (6).png",
    intro: "Airtec Solutions manufactures and supplies prefabricated Modular Operation Theatres that meet the requirements of advanced surgical environments. Our systems are planned for cost-effective delivery when the project timeline is tight.",
    benefits: ["Pre-fabricated construction for faster project delivery", "Easy-install and portable modular configuration", "Complete support from planning and design to installation", "Specialist HVAC expertise with after-sales support"],
    applications: ["Hospitals", "Advanced operation theaters", "Healthcare expansion projects", "Portable and time-critical clinical facilities"],
  },
  {
    slug: "seamless-operation-theater",
    number: "15",
    title: "Seamless Operation Theater",
    shortTitle: "Seamless OT",
    description: "Stainless-steel modular seamless operation theaters designed for cleanability, moisture resistance and long service life.",
    image: "/solutions/1 (6).png",
    intro: "Airtec Solutions manufactures Seamless Operation Theater systems that support a highly filtered, bacteria-free operating environment. Their continuous, seamless interior is designed for easy cleaning and dependable performance in demanding hospital conditions.",
    benefits: ["Stainless-steel modular construction with a seamless, easy-to-clean finish", "Supports bacteria, mould and yeast growth protection", "Moisture and freeze-thaw resistance for demanding environments", "15-year durability with low maintenance and effective serviceability"],
    applications: ["Hospitals", "Operation theaters", "High-humidity healthcare areas", "Surgical and critical-care environments"],
  },
  {
    slug: "stainless-steel-operation-theater",
    number: "16",
    title: "Stainless Steel Operation Theater",
    shortTitle: "Stainless Steel OT",
    description: "Expertly crafted stainless-steel modular operation theaters with spacious planning and elevated durability for hospitals.",
    image: "/solutions/1 (6).png",
    intro: "Airtec Solutions manufactures and supplies Stainless Steel Operation Theaters designed to meet the requirements of advanced operation theaters. Each modular system combines a strong, hygienic material with thoughtful planning for the people and equipment inside the room.",
    benefits: ["Expertly crafted stainless-steel modular construction", "Rightly spacious planning around the clinical workflow", "Elevated durability for demanding hospital use", "Designed for the requirements of advanced operation theaters"],
    applications: ["Hospitals", "Advanced operation theaters", "Specialist surgical facilities", "Healthcare expansion projects"],
  },
  {
    slug: "pu-wall-operation-theater",
    number: "17",
    title: "PU Wall Operation Theater",
    shortTitle: "PU Wall OT",
    description: "Paint-coated PU wall modular operation theaters with adjustable light, easy installation and high illumination for hospitals.",
    image: "/solutions/1 (6).png",
    intro: "Airtec Solutions provides PU Wall Operation Theaters for hospitals that need a practical, high-quality modular clinical interior. The PU wall system combines a paint-coated surface with adjustable lighting and high illumination.",
    benefits: ["PU modular wall construction", "Paint-coated surface treatment", "Adjustable light for the operating environment", "Easy to install with high illumination"],
    applications: ["Hospitals", "Operation theaters", "Modular healthcare interiors", "Surgical facilities across India"],
  },
  {
    slug: "hardwall-operation-theater",
    number: "18",
    title: "Hardwall Operation Theater",
    shortTitle: "Hardwall OT",
    description: "Stainless-steel modular hardwall operation theaters with controlled humidity, low noise and complete HVAC support for hospitals.",
    image: "/solutions/1 (6).png",
    intro: "Airtec Solutions manufactures and supplies Hardwall Operation Theatres for advanced surgical environments. Our cost-effective critical-environment solutions are planned for tight timescales and supported from design through after-sales service.",
    benefits: ["Stainless-steel modular hardwall construction", "50% humidity and 42 dB noise-level specification", "Specialist purified HVAC system support", "Complete planning, production, installation and after-sales service"],
    applications: ["Hospitals", "Advanced operation theaters", "Critical healthcare environments", "Surgical facilities across India"],
  },
  {
    slug: "single-operation-theater",
    number: "19",
    title: "Operation Theater",
    shortTitle: "Single Operation Theater",
    description: "PVC modular operation theaters designed for international hygiene, safety and functionality standards in hospitals.",
    image: "/solutions/1 (6).png",
    intro: "Airtec Solutions offers state-of-the-art Modular Operation Theaters designed around hygiene, safety and functionality. High-quality walls, ceilings and panels create a durable, infection-controlled environment that integrates smoothly with advanced medical equipment.",
    benefits: ["PVC modular construction for flexible, efficient planning", "Superior infection control and air filtration support", "Spacious layout for a smooth healthcare workflow", "Premium-grade materials for long-lasting durability"],
    applications: ["Hospitals", "Operation theaters", "Advanced surgical facilities", "Healthcare projects requiring controlled environments"],
  },
];

// Keep renamed URLs available in the static export so existing bookmarks and
// previously indexed links render safely while the new manufacturer URLs remain canonical.
const legacySolutionSlugs: Record<string, string> = {
  "modular-operation-theatre": "modular-operation-theater-manufacturer",
  "modular-cleanroom": "modular-clean-room-system-manufacturer",
};

export const getSolution = (slug: string) =>
  solutions.find((solution) => solution.slug === (legacySolutionSlugs[slug] ?? slug));

export const solutionStaticSlugs = [
  ...solutions.map(({ slug }) => slug),
  ...Object.keys(legacySolutionSlugs),
];
