export type Product = {
  slug: string;
  number: string;
  title: string;
  shortTitle: string;
  category: string;
  description: string;
  intro: string;
  image: string;
  features: string[];
  applications: string[];
  specification: [string, string][];
};

const productImages = [
  "/solutions/1 (1).png",
  "/solutions/1 (5).png",
  "/solutions/1 (4).png",
  "/solutions/1 (3).png",
  "/solutions/1 (2).png",
  "/solutions/1 (6).png",
];

const makeProduct = (
  number: string,
  slug: string,
  title: string,
  category: string,
  description: string,
  intro: string,
  features: string[],
  applications: string[],
  specification: [string, string][],
): Product => ({
  number,
  slug,
  title,
  shortTitle: title,
  category,
  description,
  intro,
  image: productImages[(Number(number) - 1) % productImages.length],
  features,
  applications,
  specification,
});

export const products: Product[] = [
  makeProduct("01", "cleanroom-panels", "Cleanroom Panels", "Modular Envelope Systems", "Seamless cleanroom wall and ceiling panels engineered for hygienic, durable controlled environments.", "Airtec cleanroom panels create a smooth, sealed envelope around your process. We coordinate panel layouts, service interfaces and finish details to support reliable hygiene and day-to-day maintenance.", ["Smooth, non-porous, cleanable surfaces", "Flush joints and sealed perimeter detailing", "Modular layout for efficient installation", "Service-ready coordination for clean spaces"], ["Pharmaceutical cleanrooms", "Hospitals and operation theatres", "Laboratories", "Medical device facilities"], [["Surface", "Pre-finished hygienic skin"], ["Configuration", "Wall and ceiling systems"], ["Finish", "Custom colour options"], ["Integration", "Doors, windows and services"]]),
  makeProduct("02", "hpl-puf-panels", "HPL / PUF Panels", "Insulated Panel Systems", "High-pressure laminate and insulated PUF panel systems for robust, thermally efficient controlled spaces.", "Built for demanding interiors, our HPL and PUF panel systems pair durable finishes with practical insulation performance. The final configuration is selected around the room use, cleaning regime and environmental target.", ["Impact-resistant HPL finish options", "Insulated PUF core configurations", "Low-maintenance hygienic surfaces", "Modular details for fast site assembly"], ["Cleanroom envelopes", "Cold and temperature-controlled rooms", "Healthcare interiors", "Pharmaceutical production"], [["Facing", "HPL or coated metal options"], ["Core", "PUF insulated construction"], ["Assembly", "Modular tongue-and-groove system"], ["Use", "Walls, partitions and ceilings"]]),
  makeProduct("03", "hepa-filter", "HEPA Filter", "Air Filtration", "High-efficiency particulate air filtration for critical zones where clean, dependable airflow matters.", "Airtec HEPA filter solutions are specified as part of a practical airflow strategy, helping control airborne particulate in sensitive healthcare, laboratory and manufacturing areas.", ["High-efficiency particulate filtration", "Terminal and air-handling integration", "Options for ceiling-grid installations", "Accessible service and replacement planning"], ["Operation theatres", "Cleanrooms", "Laboratories", "Critical manufacturing areas"], [["Filtration", "HEPA-grade particulate control"], ["Installation", "Terminal or AHU integration"], ["Housing", "Cleanroom compatible options"], ["Support", "Selection and installation guidance"]]),
  makeProduct("04", "ahu", "Air Handling Unit", "HVAC Systems", "Engineered air handling units that support temperature, humidity, filtration and pressure-control strategies.", "An AHU is central to a controlled environment. Airtec helps configure air handling around required air changes, filtration stages, environmental stability and maintainable performance.", ["Application-led airflow and filtration design", "Temperature and humidity coordination", "Pressure-differential support", "Maintainability considered from the start"], ["Cleanrooms", "Hospitals and OT suites", "Pharmaceutical facilities", "Research laboratories"], [["Function", "Conditioned and filtered air supply"], ["Control", "Temperature, humidity and pressure support"], ["Filtration", "Multi-stage options including HEPA"], ["Configuration", "Project-specific sizing"]]),
  makeProduct("05", "laminar-airflow", "Laminar Airflow", "Clean Air Equipment", "Unidirectional, HEPA-filtered airflow systems for contamination-sensitive work zones.", "Laminar airflow equipment creates a focused clean-air zone over the critical work area. We configure the system around the process, product, operator access and cleaning workflow.", ["Focused unidirectional airflow", "HEPA-filtered air at the work zone", "Cleanable, practical construction", "Configuration for process and available space"], ["Aseptic preparation", "Laboratory workstations", "Inspection and sampling", "Medical device assembly"], [["Air pattern", "Unidirectional laminar flow"], ["Filtration", "HEPA-filtered supply air"], ["Format", "Vertical or horizontal options"], ["Use", "Critical work-zone protection"]]),
  makeProduct("06", "pass-box", "Pass Box", "Material Transfer", "Controlled material-transfer chambers that protect cleanroom zoning and workflow.", "Airtec pass boxes make it easier to move materials between areas without compromising the room boundary. Interlock, finish and size can be planned around the transfer procedure.", ["Controlled transfer between room zones", "Interlock options to reduce cross-contamination", "Flush, easy-clean internal surfaces", "Sizes planned for the material path"], ["Pharmaceutical material transfer", "Laboratories", "Cleanroom stores", "Medical device manufacturing"], [["Operation", "Manual or interlocked transfer"], ["Finish", "Hygienic cleanroom surfaces"], ["Sizing", "Project-specific clear opening"], ["Integration", "Panel-wall compatible"]]),
  makeProduct("07", "air-shower", "Air Shower", "Personnel Entry", "Personnel air showers that help remove loose particulates before entry into controlled areas.", "An air shower supports a more disciplined cleanroom entry sequence. Airtec coordinates the enclosure, airflow and access arrangement with your personnel movement and gowning process.", ["High-velocity air cleaning cycle", "Personnel-entry configurations", "Interlock options for controlled access", "Durable, cleanable enclosure details"], ["Cleanroom entry points", "Pharmaceutical production", "Electronics manufacturing", "Laboratories"], [["Purpose", "Personnel particulate removal"], ["Access", "Interlocked door options"], ["Airflow", "High-velocity recirculating air"], ["Build", "Cleanroom-ready enclosure"]]),
  makeProduct("08", "air-curtain", "Air Curtain", "Airflow Separation", "Air curtains that create an air barrier at openings to help manage dust, insects and conditioned air loss.", "Airtec air curtains are chosen around the opening size, traffic pattern and environmental need, supporting practical separation between zones without interrupting movement.", ["Air barrier at frequently used openings", "Helps reduce outside air and dust ingress", "Sized to suit doorway conditions", "Simple integration with access routes"], ["Facility entrances", "Loading and material access", "Controlled support areas", "Healthcare and commercial interiors"], [["Purpose", "Air barrier at openings"], ["Mounting", "Doorway or opening mounted"], ["Sizing", "Matched to opening width"], ["Use", "Traffic-heavy access points"]]),
  makeProduct("09", "cleanroom-doors", "Cleanroom Doors", "Controlled Access", "Flush, hygienic cleanroom doors designed for controlled access, durability and easy maintenance.", "Cleanroom doors need to work reliably with the room envelope and operational flow. We provide cleanable, well-finished door solutions coordinated with panels, vision needs and access control.", ["Flush, cleanable door faces", "Sealed frame and panel interfaces", "Vision-panel and hardware options", "Configurations for controlled movement"], ["Cleanrooms", "Operation theatres", "Laboratories", "Pharma and medical facilities"], [["Finish", "Flush hygienic surface"], ["Options", "Vision panels and hardware"], ["Interface", "Panel-system compatible"], ["Use", "Controlled area access"]]),
  makeProduct("10", "cleanroom-windows", "Cleanroom Windows", "Observation & Visibility", "Flush cleanroom glazing systems that provide visibility without compromising the hygienic envelope.", "Airtec cleanroom windows are detailed for a neat, sealed finish within the modular wall system, giving teams the visibility they need across controlled spaces.", ["Flush glazing for smooth wall transitions", "Sealed interfaces for easy cleaning", "Observation without unnecessary entry", "Integrated with cleanroom panels"], ["Cleanroom corridors", "Operation theatres", "Laboratories", "Controlled manufacturing"], [["Glazing", "Flush cleanroom window system"], ["Interface", "Integrated panel-frame detail"], ["Purpose", "Observation and visibility"], ["Finish", "Smooth, easy-clean perimeter"]]),
  makeProduct("11", "cleanroom-flooring", "Cleanroom Flooring", "Hygienic Floor Systems", "Seamless, durable flooring solutions designed for cleanability and dependable performance in controlled spaces.", "A good cleanroom floor completes the hygienic envelope. We help select compatible flooring around traffic, cleaning chemicals, room use and the desired wall-to-floor finish.", ["Smooth, cleanable floor surfaces", "Durable options for operational traffic", "Coved detailing for hygienic transitions", "Selection based on room and cleaning use"], ["Cleanrooms", "Hospitals and OT suites", "Laboratories", "Pharmaceutical production"], [["Surface", "Seamless hygienic finish options"], ["Detail", "Coved wall-to-floor transitions"], ["Selection", "Matched to traffic and cleaning"], ["Use", "Controlled environments"]]),
  makeProduct("12", "sampling-booth", "Sampling Booth", "Process Containment", "Clean-air sampling booths that help protect operators, materials and surrounding environments during sampling activity.", "Airtec sampling booths are planned around the material, sampling sequence and protection requirement. The booth helps create a controlled local environment within the broader facility workflow.", ["Controlled local work zone", "Airflow designed around sampling activity", "Cleanable internal finishes", "Workflow-led access and layout"], ["Raw-material sampling", "Pharmaceutical QC", "Laboratories", "Controlled production support"], [["Purpose", "Controlled sampling activity"], ["Airflow", "Process-led clean-air design"], ["Construction", "Hygienic cleanable enclosure"], ["Planning", "Sized around sampling workflow"]]),
  makeProduct("13", "dispensing-booth", "Dispensing Booth", "Process Containment", "Dispensing booths that help maintain a controlled, clean work zone for powder and material dispensing operations.", "Our dispensing booths are configured around material handling, operator access and local containment needs, helping teams perform routine dispensing within a more controlled environment.", ["Local clean-air work zone", "Workflow-conscious dispensing layout", "Durable, cleanable construction", "Coordination with room airflow strategy"], ["Pharmaceutical dispensing", "Raw-material handling", "Formulation areas", "Controlled manufacturing"], [["Purpose", "Material dispensing control"], ["Airflow", "Local clean-air configuration"], ["Construction", "Hygienic enclosure design"], ["Integration", "Coordinated with facility HVAC"]]),
  makeProduct("14", "ot-control-panel", "OT Control Panel", "Operation Theatre Systems", "Centralized operation theatre control panels for coordinated control and monitoring of critical room functions.", "Airtec OT control panels bring essential room controls into one clear, accessible interface. The configuration is planned around the theatre workflow and the systems that need to be monitored.", ["Centralized room-control interface", "Configurable around OT functions", "Clear, accessible operating layout", "Coordinated with modular OT systems"], ["Modular operation theatres", "Specialist surgical rooms", "Hospital upgrades", "Critical-care environments"], [["Purpose", "Centralized OT control"], ["Configuration", "Project-specific function layout"], ["Integration", "OT equipment and services"], ["Location", "Accessible theatre wall installation"]]),
  makeProduct("15", "ot-lights", "OT Lights", "Operation Theatre Systems", "Surgical lighting solutions designed to support reliable illumination in modern operation theatres.", "Airtec helps coordinate OT lighting with the wider theatre design, considering surgical access, ceiling layout and the working needs of the clinical team.", ["Focused surgical illumination", "Theatre-ready mounting solutions", "Coordination with ceiling and services", "Selection support for clinical workflows"], ["Major operation theatres", "Minor operation theatres", "Specialist surgery rooms", "Hospital projects"], [["Purpose", "Surgical task illumination"], ["Mounting", "Theatre ceiling configuration"], ["Coordination", "Integrated with OT layout"], ["Use", "Clinical and surgical environments"]]),
];

export const getProduct = (slug: string) => products.find((product) => product.slug === slug);
